spring:
    application:
        name: santander_dev_week
    datasource:
        url: jdbc:h2:mem:sdw
        driver-class-name: org.h2.Driver
        username: sa
        password: ""
    h2:
        console:
            enabled: true
